# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VindTechnologies
                                 A QGIS plugin
 Plugin synching QGIS project with Vind projects
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-08-30
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Vind Technologies
        email                : support@vind.ai
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsProject, QgsJsonExporter, QgsMapLayerType
import http.client
import json
import time
import uuid
from datetime import datetime


# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .vind_technologies_dialog import VindTechnologiesDialog
import os.path


class VindTechnologies:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'VindTechnologies_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Vind Technologies')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('VindTechnologies', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/vind_technologies/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Vind synch'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Vind Technologies'),
                action)
            self.iface.removeToolBarIcon(action)

    def add_id_and_name(self, f):
        new_id = str(uuid.uuid4())
        f["id"] = new_id
        f["properties"]["id"] = new_id
        if "name" not in f["properties"]:
            f["properties"]["name"] = "Synced feature"

    def multi_feature_to_single(self, features):
        single_features = []
        for feature in features:
            if "Multi" in feature["geometry"]["type"]:
                single_type = feature["geometry"]["type"].split("Multi")[1]
                for coords in feature["geometry"]["coordinates"]:
                    single_features.append({**feature, "geometry": {"type": single_type, "coordinates": coords}})
            else:
                single_features.append(feature)
        return single_features

    def sync_project(self):
        self.dlg.status.setStyleSheet("color: lightgreen")
        self.dlg.status.setText("Synching data...")
        token = self.dlg.tokenTextBox.text()
        if(len(token)) < 100:
            self.dlg.status.setStyleSheet("color: yellow")
            self.dlg.status.setText("Incorrect token? Go to readme to learn how to set it correctly")
            return

        url = self.dlg.urlTextBox.text()
        split_url = url.split("/")
        if len(split_url) < 4:
            self.dlg.status.setStyleSheet("color: yellow")
            self.dlg.status.setText("Incorrect url? Go to readme to learn how to set it correctly")
            return

        if split_url[3] == "design":
            customer_id = split_url[5]
            project_id = split_url[6]
        else:
            customer_id = split_url[4]
            project_id = split_url[5]

        tree = QgsProject.instance().layerTreeRoot()

        geojson_features = []
        layers = [layer for layer in QgsProject.instance().mapLayers().values() if layer.type() == QgsMapLayerType.VectorLayer and tree.findLayer(layer).isVisible() is True]

        print(f"Found {len(layers)} layers")

        for layer in layers:
            exporter = QgsJsonExporter(layer)
            features = list(layer.getFeatures())
            geojson_features += [json.loads(exporter.exportFeature(feature)) for feature in features]

        print(geojson_features)

        geojson_features = self.multi_feature_to_single(geojson_features)
        for feature in geojson_features:
            self.add_id_and_name(feature)

        timestamp = int(round(time.time() * 1000))

        conn = http.client.HTTPSConnection("app.vind.ai")
        conn.request("PUT", f"/api/project-data/{customer_id}/{project_id}", json.dumps({"features": geojson_features, "timestamp": timestamp}), {"content-type": "application/json", "Authorization": f"Bearer {token}"})
        res = conn.getresponse()

        print("res.status", res.status)

        if res.status != 200:
            self.dlg.status.setStyleSheet("color: red")
            self.dlg.status.setText(f"Unable to synch, server responded with {res.status}, please contact support@vind.ai if you have done everything stated in the readme")
        else:
            self.dlg.status.setStyleSheet("color: green")
            self.dlg.status.setText(f"Project has been synchronized - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = VindTechnologiesDialog()

        # show the dialog
        self.dlg.show()

        self.dlg.pushButton.clicked.connect(self.sync_project)
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            pass
